### ISSUE TITLE
As a GDPR-compliant developer, we want to ensure user's ability to be deleted from Chirp!

### ISSUE THREAD

**Issue by frenchtaco** [ITU-BDSA23-GROUP6/Chirp#124]
### GOAL
Create a button on user page that gives the user the option to be forgotten by Chirp, see [this](https://github.com/itu-bdsa/lecture_notes/blob/main/sessions/session_12/README_PROJECT.md). 

### Acceptance Criteria: 
- [x] Create a forget me-button available for authenticated users only.
- [x] The button should delete all information about this user, e.g., name, email address, links to other users that this user is following

* There is a link to the book referencing a possible implementation of this.

**Comment by mikto97** [comment]
Done and merged
