### ISSUE TITLE
JSON Serialization and Deserialization. As a developer and user, the need to change the type back and fourth between JSON is need to handle and store the data. 

### ISSUE THREAD

**Issue by millemol1en** [ITU-BDSA23-GROUP6/Chirp#49]
Key Requirements:
   01. Make it so objects being called with GET are Deserialize and handled (either displaced in Terminal or HTML).
   02. Make it so objects being called with POST are Serialized to JSON and stored.

Specification:
   # Perhaps use NewtonSoft Nuget Package?
   # Either that or use JsonSerializer Class (System.Text.Json)

**Comment by yekxp** [comment]
Hello, my name is Jakub and I am a student of Technical University in Kosice and software developer in Siemens Healthineers and I would be very happy if I could work on this issue. It would be the part of the course where we have to help a project on GitHub. Could you assign me to it, please?
